In [1]:
import torch

In [2]:
# 生成顺序排列的一维张量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# number of elements
x.numel()

12

<br></br>
<font size=4>**要改变一个张量的形状而不改变元素数量和元素值， 我们可以调用reshape函数。**</font>

In [4]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

<br></br>
<font size=4>**使用全0、全1、其他常量或者从特定分布中随机采样的数字**</font>

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

<br></br>
<font size=4>**通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值**</font>

In [8]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

<br></br>
<font size=4>**常见的标准算术运算符（+、 -、 *、 /和 **）都可以被升级为按元素运算**</font>

In [9]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

<br></br>
<font size=4>**按元素方式应用更多的计算**</font>

In [10]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

<br></br>
<font size=4>**我们也可以把多个张量连结在一起**</font>

In [15]:
X = torch.arange(12, dtype = torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)    # 默认是dim=0   
#其shape的对应位 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

<br></br>
<font size=4>**通过逻辑运算符构建二元张量**</font>

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

<br></br>
<font size=4>**对张量中的所有元素进行求和会产生一个只有一个元素的张量**</font>

In [18]:
X.sum()

tensor(66.)

<br></br>
<font size=4>**即使形状不同， 我们仍然可以通过调用广播机制(前提是维度一样)来执行元素操作**</font>

In [19]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

<br></br>
<font size=4>**可以用[-1]选择最后一个元素， 可以用[1:3]选择第二个和第三个元素**</font>

In [21]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

<br></br>
<font size=4>**为多个元素赋值相同的值， 我们只需要索引所有元素，然后为它们赋值**</font>

In [22]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

<br></br>
<font size=4>**运行一些操作可能会导致为新结果分配内存**</font>

In [24]:
before = id(Y)
Y = Y + X
id(Y) == before

False

<br></br>
<font size=4>**执行原地操作**</font>

In [25]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1568420584960
id(Z): 1568420584960


<br></br>
<font size=4>**如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。**</font>

In [27]:
before = id(X)
X += Y
id(X) == before

True

<br></br>
<font size=4>**转换为NumPy张量**</font>

In [28]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

<br></br>
<font size=4>**将大小为1的张量转换为Python标量**</font>

In [31]:
a = torch.tensor(3.5)
a, a.item(), float(a), int(a)

(tensor(3.5000), 3.5, 3.5, 3)