In [32]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

<br></br>
<font size=4>**在我们计算y关于x的梯度之前， 我们需要一个地方来存储梯度。**</font>

In [33]:
x.requires_grad_(True) # 等价于 x = torch.arange(4, requires_grad=True)
print(x.grad) # 默认值是None

None


In [34]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

<br></br>
<font size=4>**通过调用反向传播函数来自动计算y关于x每个分量的梯度**</font>

In [35]:
y.backward(retain_graph=True)
x.grad

tensor([ 0.,  4.,  8., 12.])

In [36]:
x.grad == 4 * x

tensor([True, True, True, True])

<br></br>
<font size=4>**现在让我们计算x的另一个函数。**</font>

In [37]:
# 在默认情况下, PyTorch会累积梯度， 我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

<br></br>
<font size=4>**将某些计算移动到记录的计算图之外**</font>

In [38]:
x.grad.zero_()
y = x * x
u = y.detach() # 相当于移动到计算图之外， u不再是x的函数
z = u * x

z.sum().backward()
x.grad == u


tensor([True, True, True, True])

In [39]:
x.grad.zero_()
y.sum().backward()
x.grad 

tensor([0., 2., 4., 6.])